// Mock Data for Development and Demo

export const mockUsers = [
  {
    _id: "user1",
    username: "johndoe",
    email: "john@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    bio: "Full-stack developer | Open source enthusiast",
    followers: 245,
    following: 189,
    repositories: 42,
  },
  {
    _id: "user2",
    username: "janedoe",
    email: "jane@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    bio: "Frontend developer | React expert",
    followers: 512,
    following: 234,
    repositories: 28,
  },
  {
    _id: "user3",
    username: "alexsmith",
    email: "alex@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    bio: "DevOps Engineer | Cloud Architecture",
    followers: 389,
    following: 156,
    repositories: 35,
  },
];

export const mockRepositories = [
  {
    _id: "repo1",
    name: "awesome-react-app",
    description: "A modern React application with best practices and clean architecture",
    owner: mockUsers[0],
    visibility: true,
    stars: 1245,
    forks: 234,
    language: "JavaScript",
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days ago
    issues: 12,
    pullRequests: 5,
    branches: 8,
    commits: 156,
    size: "2.4 MB",
    license: "MIT",
    topics: ["react", "javascript", "frontend", "web-development"],
  },
  {
    _id: "repo2",
    name: "nodejs-api-server",
    description: "RESTful API server built with Node.js, Express, and MongoDB",
    owner: mockUsers[0],
    visibility: true,
    stars: 892,
    forks: 145,
    language: "TypeScript",
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    issues: 8,
    pullRequests: 3,
    branches: 5,
    commits: 234,
    size: "1.8 MB",
    license: "Apache-2.0",
    topics: ["nodejs", "express", "mongodb", "api", "backend"],
  },
  {
    _id: "repo3",
    name: "machine-learning-toolkit",
    description: "Python toolkit for machine learning experiments and model training",
    owner: mockUsers[1],
    visibility: true,
    stars: 2341,
    forks: 567,
    language: "Python",
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    issues: 23,
    pullRequests: 11,
    branches: 12,
    commits: 445,
    size: "5.6 MB",
    license: "MIT",
    topics: ["python", "machine-learning", "ai", "data-science"],
  },
  {
    _id: "repo4",
    name: "devops-automation",
    description: "Infrastructure as Code and CI/CD automation scripts",
    owner: mockUsers[2],
    visibility: false,
    stars: 456,
    forks: 89,
    language: "Shell",
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    issues: 5,
    pullRequests: 2,
    branches: 4,
    commits: 178,
    size: "892 KB",
    license: "GPL-3.0",
    topics: ["devops", "automation", "docker", "kubernetes"],
  },
  {
    _id: "repo5",
    name: "mobile-app-flutter",
    description: "Cross-platform mobile application built with Flutter",
    owner: mockUsers[1],
    visibility: true,
    stars: 678,
    forks: 123,
    language: "Dart",
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    issues: 15,
    pullRequests: 7,
    branches: 6,
    commits: 289,
    size: "3.2 MB",
    license: "MIT",
    topics: ["flutter", "dart", "mobile", "android", "ios"],
  },
  {
    _id: "repo6",
    name: "data-visualization-dashboard",
    description: "Interactive data visualization dashboard using D3.js and React",
    owner: mockUsers[0],
    visibility: true,
    stars: 1567,
    forks: 289,
    language: "JavaScript",
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    issues: 18,
    pullRequests: 9,
    branches: 10,
    commits: 367,
    size: "4.1 MB",
    license: "MIT",
    topics: ["d3js", "react", "visualization", "dashboard", "analytics"],
  },
];

export const mockCommits = [
  {
    id: "commit1",
    sha: "a1b2c3d",
    message: "Add user authentication with JWT tokens",
    author: mockUsers[0],
    date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    branch: "main",
    filesChanged: 5,
    additions: 234,
    deletions: 45,
  },
  {
    id: "commit2",
    sha: "e4f5g6h",
    message: "Fix: Resolve memory leak in data processing",
    author: mockUsers[0],
    date: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    branch: "main",
    filesChanged: 2,
    additions: 12,
    deletions: 8,
  },
  {
    id: "commit3",
    sha: "i7j8k9l",
    message: "Feature: Add real-time notifications",
    author: mockUsers[1],
    date: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    branch: "feature/notifications",
    filesChanged: 8,
    additions: 456,
    deletions: 23,
  },
  {
    id: "commit4",
    sha: "m0n1o2p",
    message: "Update dependencies to latest versions",
    author: mockUsers[0],
    date: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    branch: "main",
    filesChanged: 1,
    additions: 15,
    deletions: 15,
  },
  {
    id: "commit5",
    sha: "q3r4s5t",
    message: "Refactor: Improve code organization and structure",
    author: mockUsers[2],
    date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    branch: "main",
    filesChanged: 12,
    additions: 189,
    deletions: 234,
  },
];

export const mockBranches = [
  {
    name: "main",
    current: true,
    commit: "a1b2c3d",
    created: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    protected: true,
  },
  {
    name: "develop",
    current: false,
    commit: "e4f5g6h",
    created: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    protected: false,
  },
  {
    name: "feature/authentication",
    current: false,
    commit: "i7j8k9l",
    created: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    protected: false,
  },
  {
    name: "feature/notifications",
    current: false,
    commit: "m0n1o2p",
    created: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    protected: false,
  },
  {
    name: "bugfix/memory-leak",
    current: false,
    commit: "q3r4s5t",
    created: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    protected: false,
  },
];

export const mockTags = [
  {
    name: "v1.0.0",
    commit: "a1b2c3d",
    message: "First stable release",
    created: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    author: mockUsers[0],
  },
  {
    name: "v1.1.0",
    commit: "e4f5g6h",
    message: "Feature release with notifications",
    created: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    author: mockUsers[0],
  },
  {
    name: "v1.1.1",
    commit: "i7j8k9l",
    message: "Bug fix release",
    created: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    author: mockUsers[1],
  },
];

export const mockIssues = [
  {
    _id: "issue1",
    title: "Add dark mode support",
    description: "Users are requesting a dark mode theme option for better readability at night.",
    status: "open",
    priority: "high",
    author: mockUsers[1],
    assignee: mockUsers[0],
    labels: ["enhancement", "ui"],
    comments: 8,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "issue2",
    title: "Fix login redirect issue",
    description: "After successful login, users are not being redirected to the dashboard.",
    status: "in-progress",
    priority: "critical",
    author: mockUsers[2],
    assignee: mockUsers[0],
    labels: ["bug", "authentication"],
    comments: 5,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    _id: "issue3",
    title: "Improve API response time",
    description: "Some API endpoints are taking too long to respond, affecting user experience.",
    status: "open",
    priority: "medium",
    author: mockUsers[0],
    assignee: mockUsers[2],
    labels: ["performance", "backend"],
    comments: 12,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "issue4",
    title: "Add unit tests for authentication module",
    description: "Need comprehensive unit tests to ensure authentication works correctly.",
    status: "closed",
    priority: "medium",
    author: mockUsers[1],
    assignee: mockUsers[1],
    labels: ["testing", "authentication"],
    comments: 3,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockActivity = [
  {
    id: "act1",
    type: "commit",
    user: mockUsers[0],
    repo: mockRepositories[0],
    message: "Pushed 3 commits to main",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act2",
    type: "issue",
    user: mockUsers[1],
    repo: mockRepositories[0],
    message: "Opened issue #12: Add dark mode support",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act3",
    type: "star",
    user: mockUsers[2],
    repo: mockRepositories[2],
    message: "Starred machine-learning-toolkit",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act4",
    type: "fork",
    user: mockUsers[1],
    repo: mockRepositories[1],
    message: "Forked nodejs-api-server",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act5",
    type: "branch",
    user: mockUsers[0],
    repo: mockRepositories[0],
    message: "Created branch feature/notifications",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
];

// Helper function to get time ago
export const getTimeAgo = (date) => {
  const seconds = Math.floor((new Date() - new Date(date)) / 1000);
  
  let interval = seconds / 31536000;
  if (interval > 1) return Math.floor(interval) + " years ago";
  
  interval = seconds / 2592000;
  if (interval > 1) return Math.floor(interval) + " months ago";
  
  interval = seconds / 86400;
  if (interval > 1) return Math.floor(interval) + " days ago";
  
  interval = seconds / 3600;
  if (interval > 1) return Math.floor(interval) + " hours ago";
  
  interval = seconds / 60;
  if (interval > 1) return Math.floor(interval) + " minutes ago";
  
  return Math.floor(seconds) + " seconds ago";
};

// Language colors (GitHub style)
export const languageColors = {
  JavaScript: "#f1e05a",
  TypeScript: "#3178c6",
  Python: "#3572A5",
  Java: "#b07219",
  Go: "#00ADD8",
  Rust: "#dea584",
  Ruby: "#701516",
  PHP: "#4F5D95",
  C: "#555555",
  "C++": "#f34b7d",
  "C#": "#178600",
  Swift: "#ffac45",
  Kotlin: "#A97BFF",
  Dart: "#00B4AB",
  Shell: "#89e051",
  HTML: "#e34c26",
  CSS: "#563d7c",
  Vue: "#41b883",
  React: "#61dafb",
};
